# -*- coding: utf-8 -*-
"""Final Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aRd8HYtBfyCxgtD6NBoEFEGKCTLeaSrS

Best Buy Retail Store-Point of Sale System
"""

# Predefined Product Catalog
# Below are 10 products including groceries, beverages and household items.
# Product name, price and stock
Low_Stock_Threshold = 5
product_catalog ={
    "Rice":               {"price":25.00, "stock": 150},
    "Beer":               {"price":18.50, "stock": 120},
    "Sugar":              {"price":8.00,  "stock": 100},
    "Bread":              {"price":5.50,  "stock": 25},
    "Milk":               {"price":7.00,  "stock": 75},
    "Spam":               {"price":12.00, "stock": 20},
    "Bottled Water":      {"price":2.50,  "stock": 100},
    "Laundry Soap":       {"price":9.00,  "stock": 15},
    "Dishwashing liquid": {"price":10.00, "stock": 18},
    "Sardines":           {"price":6.00,  "stock": 60},
    "Coffee":             {"price":14.00, "stock": 90},
    "Shampoo":            {"price":15.00, "stock": 80},
}

# Displaying available products
def display_products():
  print("\nAvailable Products:")
  print(f"{'Product':<26} {'Price':>6}{'Stock':>8}")


  for product_name, info in product_catalog.items():
    if info["stock"] < Low_Stock_Threshold:
       print(f" {product_name:<24} ${info['price']:>6.2f}{info['stock']:>8} ('Low Stock!')")
    else:
      print(f" {product_name:<24} ${info['price']:>6.2f}{info['stock']:>8}")

display_products()

# Adding items to the cart

def add_to_cart(cart):
    print("\nAdd Item to the Cart")

    # Asking the cashier for the product name
    product_name = input("Enter product name: ").strip().lower()

    # Searching the catalog with case-insensitive match
    matched_key = None
    for key in product_catalog:
        if product_name in key.lower(): # partial match
           matched_key = key
           break

    # Validating that the product exists in the catalog
    if matched_key is None:
        print("Product not found.")
        return

    product_name = matched_key

    # Asking the cashier for the quantity they want to add
    try:
        quantity = int(input(f"Enter quantity for '{product_name}': "))

        # Validating that the quantity is positive
        if quantity <= 0:
            print("Please enter a positive quantity.")
            return
    except ValueError:
        print("Invalid input. Please enter a number greater than 0.")
        return

    # Checking stock availability
    available_stock = product_catalog[product_name]["stock"]

    # Checking how many of this item is are already in the cart
    already_in_cart = cart.get(product_name,{}).get("quantity", 0)

    # Calculating the total amount needed (already in the cart + new request)
    total_needed = already_in_cart + quantity

    # Comparing the total needed with what is already in the cart

    if total_needed > available_stock:
      print(f"Not enough stock. Available: {available_stock}.")
      return

    # Updating item quantity that is already in the cart
    # Adding new item to the cart
    if product_name in cart:
        cart[product_name]["quantity"] += quantity
    else:
        cart[product_name] = {
           "quantity": quantity,
           "unit_price": product_catalog[product_name]["price"]
       }
    # Confirming that the item that were added
    print(f"{quantity} x '{product_name}' has been added to your cart.")

# Removing item from cart
def remove_from_cart(cart):
    if not cart:
        print(" Your cart is empty")
        return

    print("\nRemove Item from Cart:")
    print("Items in your cart:")
    for item, info in cart.items():
        print(f"{item:<25} Qty: {info['quantity']:>3}  Unit Price: ${info['unit_price']:.2f}")

    product_name= input("\nEnter the product name to remove from your cart ( or 'no' to keep items):").strip()

    if product_name.lower() == "no":
        print("\nNo items removed.")
        return

    if product_name not in cart:
        print(f"'{product_name}' is not in your cart.")
        return

    del cart[product_name]
    print(f"'{product_name}' has been removed from your cart.")

# Viewing the contents in the cart
def view_cart(cart):
    if not cart:
      print("\nYour cart is empty.")
      return

    print("\nYour Cart:")
    print(f"{'Product':<25} {'Quantity':>8} {'Unit Price':>12} {'Total':>12}")
    subtotal = 0
    for product_name, info in cart.items():
        line_total = info["quantity"]*info["unit_price"]
        subtotal += line_total

        print(f" {product_name:<25} {info['quantity']:>8} ${info['unit_price']:>11.2f} ${line_total:>9.2f}")
    print(f"{'Subtotal':<25} ${subtotal:>9.2f}")

# Checking out and payment Processing
def checkout_and_pay(cart):
    if not cart:
     print("\nYour cart is empty. Please add items before checking out.")
     return
  # Calculate subtotal
    subtotal = sum(info["quantity"]*info["unit_price"] for info in cart.values())

  # Apply discount if subtotal is more than $5000
    discount = 0
    if subtotal > 5000:
       discount = subtotal * 0.05
       print("\nCongratulations! You have received a 5% discount.")

    discounted_total = subtotal - discount
    tax = discounted_total * 0.10
    total = discounted_total + tax

    # Displaying the checkout Summary
    print("\nCheckout Summary")
    print(f"Subtotal: ${subtotal:.2f}")
    print(f"Discount: ${discount:.2f}")
    print(f"Tax (10%): ${tax:.2f}")
    print(f"Total Amount Due: ${total:.2f}")

    while True:
       try:
           paid = float(input("\nEnter the amount paid by the customer: $"))
           if paid <total:
             print(f"Insufficient Funds. Please try again. Total is ${total:.2f}.")
           else:
                break
       except ValueError:
           print("Invalid input. Please enter a valid amount.")

    change = paid - total

    # Deduct purchased quantities from stock
    for product_name, info in cart.items():
        product_catalog[product_name]["stock"] -= info["quantity"]

    generate_receipt(cart, subtotal, discount, tax, total, paid, change)

    print("\nChecking stock levels.")
    for product_name in cart:
        if product_catalog[product_name]["stock"] < Low_Stock_Threshold:
           print(f" Low stock warning: {product_name} only has {product_catalog[product_name]['stock']} left!")

    print("\nTransaction completed!")

# Generating the receipt
def generate_receipt(cart, subtotal, discount, tax, total, paid, change):
  print(" BEST BUY RETAIL STORE")
  print(" Your everyday essential shop")
  print("Tel:1(649) 567-7890")
  print("\n")
  print(f"{'Product':<25} {'Qty':>5} {'Unit Price':>12} {'Total':>12}")
  print("-" * 60)

  for product_name, info in cart.items():
      line_total = info["quantity"] * info["unit_price"]
      print(
          f"{product_name:<25}"
          f"{info['quantity']:>5}"
          f"{f'${info['unit_price']:.2f}':>12}"
          f"{f'${line_total:.2f}':>12}"
      )

  print("-"* 60)

  print(f"{'Subtotal':<25} {f'${subtotal:.2f}':>12}")
  if discount > 0:
      print(f"{'Discount (5%)':<25} {f'-${discount:.2f}':>12}")
  print(f"{'Sales Tax (10%)':<25} {f'${tax:.2f}':>12}")
  print(f"{'Total Due':<25} {f'${total:.2f}':>12}")
  print(f"{'Amount Paid':<25} {f'${paid:.2f}':>12}")
  print(f"{'Change Due':<25} {f'${change:.2f}':>12}")

  print("\nThank you for shopping with us.")
  print("We look forward to seeing you again!")

def main_menu():
    print("Welcome to Best Buy Retail Store POS System")

    while True:
      cart = {}
      print("\nStarting new transaction")
      while True:
        print("\nMain Menu:")
        print("1 - View Products")
        print("2 - Add Item to Cart")
        print("3 - Remove Item from Cart")
        print("4 - View Cart")
        print("5 - Checkout & Pay")
        print("6 - Exit System")

        selection = input("\nEnter your selection: ").strip()

        if selection == "1":
           display_products()
        elif selection == "2":
           add_to_cart(cart)
        elif selection == "3":
           remove_from_cart(cart)
        elif selection == "4":
          view_cart(cart)
        elif selection == "5":
          checkout_and_pay(cart)
          break
        elif selection =="6":
          print("\nSystem closed. Goodbye. Thank you for shopping with us")
          return
        else:
         print("Invalid selection. Please enter a number from the menu.")

  # Asking if the cashier wants to start a new transaction
    another_transaction = input("\n Process another transaction? (yes/no): ").strip().lower()
    if another_transaction != "yes":
      print("\nSystem closed. Goodbye. Thank you for shopping with us.")
      return

main_menu()